### ISSUE TITLE
Consulta sobre redes Modbus

### ISSUE THREAD

**Issue by hacordero** [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs#1214]
Estimado Obijuan es un gusto ante todo saludarte desde Argentina, mira soy docente Mi nombre es Alejandro Cordero con experiencia en sistemas embebidos y estoy empezando con FPGA gracias a tus tutoriales. La consulta es si tienes algún ejemplo con icestudio de implementacion Modbus RTU, y de paso tambie Modbus TC/iP.
Desde ya agradesco tu tiempo.
Saludos

**Comment by Obijuan** [comment]
Yo no tengo hecho nada para modbus, y desconozco si en la comunidad alguien tiene algo hecho. En esto de las fpga libres está todo por hacer 😀

En cualquier caso es un proyecto muy interesante y no muy complejo de implementar, al menos la versión que va por comunicación serie. El módulo serie sí está implementado y se puede reutilizar

**Comment by hacordero** [comment]
Gracias Obijuan, intentare este año concentrarme en ello a ver que puedo hacer...soy docente de Electrónica En escuelas técnicas de Argentina y estaré implementado esta plataforma a partir de este año y con  mas fuerza el año que entra! te mantendré al tanto...tus tutoriales son lo mas...Saludos @profecordero instagram....empezaremos a subir historias de los proyectos de este año alli!

**Comment by Obijuan** [comment]
¡Gracias! :-) Te deseo muchísima suerte! Es un proyecto muy interesante y será un honor para mí estar al tanto de los avances  ¡Saludos!
