### ISSUE TITLE
No entiendo por qué se han borrado 4 tutoriales acabados.

### ISSUE THREAD

**Issue by PikiPaco** [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs#1251]
No entiendo por qué se han borrado 4 tutoriales acabados. Ayer 16 de Agosto hice 4, y hoy ya no existen. He cerrado mal Github?

**Comment by Obijuan** [comment]
No estás usando github bien. Céntrate sólo en subir una imagen a tu repo:

https://github.com/PikiPaco/Entregas-Tutorial-Electronica-Digital-FPGAs/tree/master/Tutorial-1

Y luego emites el pull request
