### ISSUE TITLE
Tutorial 16, ejercicios 1 y 2

### ISSUE THREAD

**Issue by jtavleo** [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs#1297]
Tengo el sensor TCRT5000, pero me funciona al revés, lanza un 0 cuando detecta objeto, por eso he tenido que ponerle una puerta NOT para que funcionara como se requiere en los ejercicios.

**Comment by Obijuan** [comment]
Sin problemas!! ¡Genial!  :-)   ¡Buen trabajo!
