### ISSUE TITLE
Al repositorio le pesa el culo

### ISSUE THREAD

**Issue by jaimelaborda** [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs#199]
Hola!

El repositorio pesa ya casi 600MB! :O Es una locura, me tarda mucho tiempo en hacer un Fetch y un push.

No se si es que estoy haciendo algo mal, yo de normal trabajo con GitHub Desktop en Windows y lo que hago es:

1. Hacerme fetch del repositorio original (este). En local
2. Hacer un commit con mis cambios 
3. Hacer un push a mi Fork del repositorio (esto tarda la vida!)
4. Realizar un push-request a este repositorio.

¿Estoy haciendo algo mal o la manera correcta de hacerlo es esa? ¿Se podría buscar otra manera de hacerlo? Las imagenes de capturas/etc pesan demasiado

Un saludo y mil millones de gracias!! :D

PD: Intentar comprimir las imagenes antes de subirlas con algun compresor, os dejo uno online que uso yo: http://compressjpeg.com/es/

**Comment by usainzg** [comment]
Buenas, en principio no tienes porque bajarte nada del repo, solamente tienes que tener cuidado con las nomenclaturas en las carpetas, archivos, etc.

Haces los cambios en local (añadir imagenes), los subes a tu fork y desde github, haces el pull request.

No es necesario actualizar el repo cada vez que quieras subir algo a el... Fíjate en como se llama a la carpeta de los tutos y sin problemas.

**Comment by Obijuan** [comment]
En principio, antes de subir nada es mejor sincronizarte con el repo original

Aquí se explica como sincronizarte

http://www.iearobotics.com/wiki/index.php?title=Tutorial:_Github_y_Freecad#.C2.A18_Sincron.C3.ADzate.21

aunque el repositorio pese, sólo se actualiza con las nuevas cosas, por lo que no debería tardar demasiado. La primera vez sí, luego ya sólo se carga/descarga la diferencia

De todas formas, como aquí cada uno trabajais en vuestras carpetas y en prinicpio no hay interacción entre vosotros, podrías subir sin sincronizarte. Github se encarga de mergearlo adecuadamente. No obstatante, yo te invito a que aprendas a sincronizarte,que es como normalmente se trabaja con github

Suerte!

**Comment by jaimelaborda** [comment]
Hola!

Siii, en principio lo hacia bien. Cambio el origin al upstream, hago fetch, luego push y tal.. 
El problema es que al ser imagenes y no texto como normalmente, me tarda la vida (también mi internet va a pedales.. jeje).

Pero sabiendo que no hay ningún problema con hacer pull-request sin tener el origin sincronizado, lo haré así. Tenía miedo de liarla y borrar cosas.

Mil gracias a los dos por las aclaraciones!

Un saludito,
Jaime.
