### ISSUE TITLE
Ejercicios Curso FPGA´s  - Jorge Lorenzo Núñez

### ISSUE THREAD

**Issue by JorgeLN** [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs#36]
![ejercicio - nivel 1](https://user-images.githubusercontent.com/32832294/31601942-c73e64ee-b25b-11e7-8361-b5d9ba9488cf.jpeg)
![ejercicio - nivel 2](https://user-images.githubusercontent.com/32832294/31601944-c7611b88-b25b-11e7-85a0-0cd0d195b509.jpeg)
![ejercicio - nivel 3](https://user-images.githubusercontent.com/32832294/31601945-c78324c6-b25b-11e7-9c02-8778656cf6cf.jpeg)

**Comment by JorgeLN** [comment]
Ejercicios Jorge Lorenzo Núñez

**Comment by Obijuan** [comment]
Hola Jorge!

Has enviado las imágenes como adjuntos de los comentarios del pull-request, pero en realidad los ficheros no están en el repo. Te las voy a añadir yo. El proceso es: una vez hecho el fork, te lo clonas en tu ordenador local, añades una carpeta con tus soluciones, haces git add y git commit, lo subes a tu repo remoto con git push y desde ahí haces el pull-request.

+2 BitPoints!  ¡Gracias!

**Comment by JorgeLN** [comment]
Perfecto, muchas gracias!.

La verdad es que me he creado esta mañana la cuenta en GitHUb, me he hecho
el tutorial de los pull-request pero no he conseguido hacerlo bien.

También te he mandado las cosas al google plus.

Un saludo y gracias :)

2017-10-16 14:47 GMT+02:00 Juan Gonzalez-Gomez <notifications@github.com>:
