### ISSUE TITLE
Entrega Tareas

### ISSUE THREAD

**Issue by jcubilloarr** [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs#39]
Hola Obijuan!
Entrego las tareas de la primera tutoría online.
Nunca había empleado Github para trabajar así que esta nueva experiencia también suma.
Gracias por tu trabajo y un saludo.

![img_-91px9d](https://user-images.githubusercontent.com/32846548/31622682-62529b80-b29d-11e7-84c3-c3c6d48fa9d5.jpg)
![img_429hgb](https://user-images.githubusercontent.com/32846548/31622684-628981d6-b29d-11e7-9eda-43aaa976c9f7.jpg)
![img_jmrztb](https://user-images.githubusercontent.com/32846548/31622685-62ae56a0-b29d-11e7-960f-28d644f670ae.jpg)

**Comment by Obijuan** [comment]
rHola!

¡Gracias! +2 BitPoints 

En realidad no has subido los ficheros al github. Has puesto las imágenes como parte de una issue. Las issues se usan para informar de errores encontrados.  Github es un repositorio, y cuesta un poquillo aprender a manejarlo (es una herramientas muy muy potente), pero merece la pena. Cuando aprendas podrás hacer aportaciones a cualquiera de lods proyectos existentes

Hace tiempo hice estos tutoriales para enseñar github:

http://www.iearobotics.com/wiki/index.php?title=Tutorial:_Github_y_Freecad

Como ejemplo usé ficheros de Freecad, pero en realidad el curso vale cualquier tipo de fichero

Las imágenes que me has puesto aquí ya las he subido al repo. Están en la carpeta jcubilloarr

**Comment by jcubilloarr** [comment]
Buenas tardes!
Tomo nota de tus indicaciones, entre tus tutoriales de FreeCad, FPGA y ahora GITHUB no paro. Supongo que muchos ya te lo habrán dicho, pero muchas gracias por el aporte que haces, por la dedicación y el tiempo libre que gastas difundiendo el conocimiento. Mi más sincera enhorabuena y es un placer poder contar contigo.

Un abrazo desde Aranda de Duero!

Enviado desde Correo para Windows 10

De: Juan Gonzalez-Gomez
Enviado: martes, 17 de octubre de 2017 13:58
Para: Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs
CC: jcubilloarr; Author
Asunto: Re: [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs] EntregaTareas (#39)

rHola!
¡Gracias! +2 BitPoints
En realidad no has subido los ficheros al github. Has puesto las imágenes como parte de una issue. Las issues se usan para informar de errores encontrados. Github es un repositorio, y cuesta un poquillo aprender a manejarlo (es una herramientas muy muy potente), pero merece la pena. Cuando aprendas podrás hacer aportaciones a cualquiera de lods proyectos existentes
Hace tiempo hice estos tutoriales para enseñar github:
http://www.iearobotics.com/wiki/index.php?title=Tutorial:_Github_y_Freecad
Como ejemplo usé ficheros de Freecad, pero en realidad el curso vale cualquier tipo de fichero
Las imágenes que me has puesto aquí ya las he subido al repo. Están en la carpeta jcubilloarr

**Comment by jcubilloarr** [comment]
Hola de nuevo para agradecerte la amabilidad quería compartir contigo una “chorradilla”, y es que estamos con las FPGA y con los modelos de botones y led que habéis creado, he modificado un poco el diseño para ponerle una “tapa” para que no se vean las soldaduras y para evitar posibles cortos.
Te mando los STL así como unas imágenes de cómo ha quedado.
De nuevo gracias por tu ayuda.





De: Juan Gonzalez-Gomez
Enviado: martes, 17 de octubre de 2017 13:58
Para: Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs
CC: jcubilloarr; Author
Asunto: Re: [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs] EntregaTareas (#39)

rHola!
¡Gracias! +2 BitPoints
En realidad no has subido los ficheros al github. Has puesto las imágenes como parte de una issue. Las issues se usan para informar de errores encontrados. Github es un repositorio, y cuesta un poquillo aprender a manejarlo (es una herramientas muy muy potente), pero merece la pena. Cuando aprendas podrás hacer aportaciones a cualquiera de lods proyectos existentes
Hace tiempo hice estos tutoriales para enseñar github:
http://www.iearobotics.com/wiki/index.php?title=Tutorial:_Github_y_Freecad
Como ejemplo usé ficheros de Freecad, pero en realidad el curso vale cualquier tipo de fichero
Las imágenes que me has puesto aquí ya las he subido al repo. Están en la carpeta jcubilloarr

**Comment by Obijuan** [comment]
Hola!

Te estoy escribiendo estos mensajes desde el issue que abriste en github. Puedes ver el hilo desde esta URL:

https://github.com/Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs/issues/39

Los ficheros que me has enviado no se reciben desde aquí. Es mejor que me los envies directametne a mi correo personal:  obijuan.cube@gmail.com

Estoy deseando verlos!!!!  ¡¡¡Muchas gracias!!!!  :-)

Saludos, Juan
