### ISSUE TITLE
Ejercicios 1 -2 - 3

### ISSUE THREAD

**Issue by Navas19Xd** [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs#860]
Hola obijuan te envio la captura de los ejercicios..

**Comment by Obijuan** [comment]
Hola,

No has enviado lo ejercicios, todavía. Has abierto una issue. Esto se usa para reportar errores y problemas, pero no para subir ficheros al repo. El proceso es el siguiente:

* Primero crear una copia del repositiroio de entregas (fork). Esto ya lo has hecho. Lo tienes aquí:

https://github.com/Navas19Xd/Entregas-Tutorial-Electronica-Digital-FPGAs/tree/master/Tutorial-1

* Ahora, desde ahí, pinchas en upload files, y subes los pantallazos de los ejercicios a entregar

* Emites un pull-request (pinchando en create pull-request). Esto calcula la diferencia entre tu repositorio y el mío, y me manda los cambios. Yo acepto el pull-request y te asigno los bitpoints

Pruébalo. Al principio cuesta un poco acosumbrarse, pero en cuanto haces dos entregas te haces con ello y verás que es fácil

¡Suerte!
