### ISSUE TITLE
Convalidación de bitpoints adicionales de iconos o bloques, por ejercicios no entregados

### ISSUE THREAD

**Issue by ximocat** [Obijuan/Entregas-Tutorial-Electronica-Digital-FPGAs#869]
Hola, no tengo claro cómo funciona esto. A ver si estoy en lo cierto:

1) Imaginemos que tengo 20 bitpoints adicionales por haber entregado iconos o bloques nuevos.
2) Supongamos que estoy al día de todo hasta el tutorial 24 y por tanto dispongo de dispongo de 385 bitpoint (+20 adicionales)
3)  Supongamos también que del tutorial 25 entrego los ejercicios 1, 2 y 3 pero NO ENTREGO el 4 (el libre)

¿Pasaría a tener 410 bitpoints + 15 adicionales (5 adicionales menos)? Es decir, ¿me convalidas 5 bitpoints adicionales por el ejercicio libre que también vale 5 bitpoints?

Gracias :)

**Comment by Obijuan** [comment]
Si, exactamente. De hecho, con que solo entregues 1 ejercico de cada
tutorial, el resto los podrias convalidar (no solo los libres)

La idea es que puedaso trabajar en tus propios proyectos según vas
aprendiendo. Si no te apetece hacer algun ejercicio (o no tienes el
material), no pasa nada, lo convalidas otros proyectos tuyos
